# Change these first
owner: johndavidge # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Vulnerability Feed
    url: $VULN_URL
    icon: https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://anchore.com/&size=32
    headers:
    - "x-api-key: $API_KEY"
    - "Content-Type: application/json"
  - name: ClamAV Feed
    url: $CLAMAV_URL
    icon: https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://anchore.com/&size=32
    headers:
    - "x-api-key: $API_KEY"
    - "Content-Type: application/json"
  - name: KEV Feed
    url: $KEV_URL
    icon: https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://anchore.com/&size=32
    headers:
    - "x-api-key: "
    - "Content-Type: application/json"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name theres
  baseUrl: /status-page
  #apiBaseUrl: https://p6h532xmxla356kddksbhb5gea0kccvz.lambda-url.us-east-1.on.aws/
  userContentBaseUrl: https://p6h532xmxla356kddksbhb5gea0kccvz.lambda-url.us-east-1.on.aws/
  logoUrl: https://anchore.com/wp-content/uploads/2023/01/logo-1.svg
  name: Hosted Feeds Status
  introTitle: "**Hosted Feeds Status**"
  introMessage: This is the Hosted Feeds status page lorum ipsum.
  favicon: https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://anchore.com/&size=32
  navbar:
    - title: Support
      href: https://get.anchore.com/contact/

i18n:
  footer: Service provided by [Anchore](https://anchore.com/), status page powered by [Upptime](https://upptime.js.org)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
