# Change these first
owner: johndavidge # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Google
    url: $GOOGLE_URL
  - name: Vulnerability Feed
    url: $VULN_URL
    headers:
    - "x-api-key: $API_KEY"
    - "Content-Type: application/json"
  - name: ClamAV Feed
    url: $CLAMAV_URL
    headers:
    - "x-api-key: $API_KEY"
    - "Content-Type: application/json"
  - name: KEV Feed
    url: $KEV_URL
    headers:
    - "x-api-key: "
    - "Content-Type: application/json"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name theres
  baseUrl: /status-page
  logoUrl: https://anchore.com/wp-content/uploads/2023/01/logo-1.svg
  name: Hosted Feeds Status
  introTitle: "**Hosted Feeds Status**"
  introMessage: This is a Hosted Feeds status page blah blah blah.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
